version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: clenja_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: clenja
      POSTGRES_USER: clenja_user
      POSTGRES_PASSWORD: clenja_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
